---
sidebar: sidebar 
permalink: rn/about.html 
keywords:  
summary:  
---
= À propos de cette version
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La documentation de ce site décrit l'API REST Astra Control et les technologies d'automatisation connexes, disponibles avec la version 2022 avril 22.04 d'Astra Control. En particulier, cette version de l'API REST est incluse avec les 22.04 versions correspondantes du centre de contrôle Astra et du service de contrôle Astra.

Consultez les pages et sites suivants pour plus d'informations sur cette version ainsi que sur les versions précédentes :

* link:../rn/whats_new.html["Nouveautés de l'API REST Astra Control"]
* link:../endpoints/resources.html["Ressources REST et terminaux"]
* https://docs.netapp.com/us-en/astra-control-center-2204/["Documentation Astra Control Center 22.04"^]
* https://docs.netapp.com/us-en/astra-control-service/["Documentation relative au service après-vente Astra Control"^]
* link:../aa-earlier-versions.html["Versions antérieures de la documentation d'Astra Automation"]

