---
sidebar: sidebar 
permalink: workflows/wf_create_backup.html 
keywords:  
summary:  
---
= Créez une sauvegarde pour une application gérée
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer une sauvegarde pour une application gérée spécifique. Vous pouvez utiliser la sauvegarde pour restaurer ou cloner l'application.



=== Avant de commencer

Vous devez disposer de l'ID de l'application gérée pour laquelle vous souhaitez créer une sauvegarde. Si nécessaire, vous pouvez utiliser le workflow link:wf_list_man_apps.html["Répertorier les applications gérées"] pour localiser l'application.



=== 1. Créez une sauvegarde

Effectuez l'appel de l'API REST suivant.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| POST | /Accounts/{account_ID}/k8s/v1/managedApps/{managedApp_ID}/appBackups 
|===


===== Paramètres d'entrée supplémentaires

Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| id d'application géré | Chemin | Oui. | Identifie l'application gérée sur laquelle la sauvegarde sera créée. 


| JSON | Corps | Oui. | Fournit les paramètres de la sauvegarde. Voir l'exemple ci-dessous. 
|===


===== Exemple d'entrée JSON

[source, json]
----
{
  "type": "application/astra-appBackup",
  "version": "1.0",
  "name": "backup-david-1"
}
----


===== Exemple Curl : créez une sauvegarde pour l'application

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appBackups' --header 'Content-Type: application/astra-appBackup+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --d @JSONinput
----