---
sidebar: sidebar 
permalink: workflows/wf_list_snapshots.html 
keywords:  
summary:  
---
= Répertorier les snapshots
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez afficher la liste des snapshots pris pour une application gérée spécifique.



=== Avant de commencer

Vous devez disposer de l'ID de l'application gérée pour laquelle vous souhaitez répertorier les instantanés. Si nécessaire, vous pouvez utiliser le workflow link:wf_list_man_apps.html["Répertorier les applications gérées"] pour localiser l'application.



=== 1. Dressez la liste des instantanés

Effectuez l'appel de l'API REST suivant.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| OBTENEZ | /Accounts/{account_ID}/k8s/v1/managedApps/{managedApp_ID}/appSnaps 
|===


===== Paramètres d'entrée supplémentaires

Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="15,10,10,65"]
|===
| Paramètre | Type | Obligatoire | Description 


| id d'application géré | Chemin | Oui. | Identifie l'application gérée possédant les snapshots répertoriés. 


| nombre | Requête | Non | Si `count=true` le nombre de snapshots est inclus dans la section métadonnées de la réponse. 
|===


===== Exemple de curl : renvoie tous les snapshots de l'application

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemple de boucle : renvoie tous les snapshots de l'application et du nombre

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps?count=true' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemple de sortie JSON

[source, json]
----
{
  "items": [
    {
      "id": "dc2974ae-f71d-4c81-91b5-f96cf72dc3ba",
      "metadata": {
        "createdBy": "fb093413-b6fc-4a64-a48a-afc32ada8537",
        "creationTimestamp": "2021-06-04T21:23:14Z",
        "modificationTimestamp": "2021-06-04T21:23:14Z",
        "labels": []
      },
      "snapshotAppAsset": "4547658d-cc06-4c1d-ad8a-4a05274d0db0",
      "snapshotCreationTimestamp": "2021-06-04T21:23:47Z",
      "name": "test-postgres-app-snapshot-20210604212213",
      "state": "completed",
      "stateUnready": [],
      "type": "application/astra-appSnap",
      "version": "1.0"
    }
  ],
  "metadata": {
    "count": 1
  }
}
----